# Generated by Django 3.0.8 on 2020-07-04 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentmodel',
            fields=[
                ('Student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=150)),
                ('Age', models.CharField(max_length=150)),
                ('Class', models.CharField(max_length=150)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Marksmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mathes', models.IntegerField()),
                ('Physics', models.IntegerField()),
                ('Chemistry', models.IntegerField()),
                ('English', models.IntegerField()),
                ('social_studies', models.IntegerField()),
                ('Student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='studentApi.Studentmodel')),
            ],
        ),
    ]
